# Generated by Django 5.2.12 on 2026-03-25 09:12

import api.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.FileField(upload_to=api.models.file_storage_path)),
                ('file_size_bytes', models.BigIntegerField()),
                ('filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(editable=False, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Files',
            },
        ),
    ]
