# Generated by Django 5.2.12 on 2026-03-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='display_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userfile',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
