# Generated by Django 5.2.12 on 2026-04-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userfile_display_name_userfile_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
