# Generated by Django 5.2.12 on 2026-04-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userfolder_userfile_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfolder',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
