# Generated by Django 5.2.12 on 2026-04-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_userfolder_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfile',
            name='folder',
        ),
        migrations.AddField(
            model_name='userfile',
            name='folders',
            field=models.ManyToManyField(blank=True, related_name='files', to='api.userfolder'),
        ),
    ]
