# Generated by Django 5.2.12 on 2026-04-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_userfile_folder_userfile_folders'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
