# Generated by Django 5.2.12 on 2026-04-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_userfile_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
