# Generated by Django 5.2.12 on 2026-04-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_sharedlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedlink',
            name='is_revoked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sharedlink',
            name='receipient_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sharedlink',
            name='revoked_at',
            field=models.DateTimeField(null=True),
        ),
    ]
