# Generated by Django 5.2.12 on 2026-04-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_sharedlink_is_revoked_sharedlink_receipient_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedlink',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
