# Generated by Django 5.2.12 on 2026-04-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_sharedlink_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='checksum',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 hex digest of the file content', max_length=64, null=True),
        ),
    ]
