# Generated by Django 5.2.12 on 2026-04-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_userfile_checksum'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
