# Generated by Django 5.2.12 on 2026-04-29 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_userfile_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='last_accessed_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp of the last time the owner opened/viewed this file', null=True),
        ),
    ]
