# Generated by Django 5.2.12 on 2026-04-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_userfile_last_accessed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='storage_limit_bytes',
            field=models.BigIntegerField(default=1073741824),
        ),
    ]
