# Generated by Django 5.2.12 on 2026-04-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_user_storage_limit_bytes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consumed_storage',
            field=models.BigIntegerField(default=0),
        ),
    ]
