# Generated by Django 5.2.12 on 2026-05-06 10:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_workstation_workstationinvite_workstationmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkstationVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('saved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workstation_versions', to=settings.AUTH_USER_MODEL)),
                ('workstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='api.workstation')),
            ],
            options={
                'db_table': 'WorkstationVersions',
                'ordering': ['-created_at'],
            },
        ),
    ]
