# Generated by Django 5.2.12 on 2026-05-12 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_filerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workstation',
            name='template',
        ),
        migrations.RemoveField(
            model_name='workstation',
            name='visibility',
        ),
    ]
