# Generated by Django 5.2.12 on 2026-05-14 04:38

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_workstation_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerequest',
            name='expires_at',
            field=models.DateTimeField(default=api.models.default_file_request_expiry),
        ),
    ]
