# Generated by Django 5.2.12 on 2026-05-18 06:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_filerequest_expires_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workstationversion',
            options={},
        ),
        migrations.CreateModel(
            name='ChunkedUpload',
            fields=[
                ('upload_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('total_size', models.BigIntegerField()),
                ('current_size', models.BigIntegerField(default=0)),
                ('file_path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='uploading', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ChunkedUploads',
                'ordering': ['-updated_at'],
            },
        ),
    ]
