# Generated by Django 5.2.12 on 2026-05-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_workstationversion_options_chunkedupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedlink',
            name='access_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sharedlink',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sharedlink',
            name='download_limit',
            field=models.IntegerField(default=5, help_text='Max downloads allowed. 0 means preview only.'),
        ),
    ]
