# Generated by Django 5.2.12 on 2026-05-20 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_sharedlink_access_count_sharedlink_download_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedlink',
            name='access_count',
        ),
    ]
