# Generated by Django 5.2.12 on 2026-05-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_sharedlink_access_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='userfile',
            index=models.Index(fields=['is_deleted', 'deleted_at'], name='Files_is_dele_6c4f2c_idx'),
        ),
    ]
