# Generated by Django 5.2.12 on 2026-05-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_user_disabled_at_userfile_files_is_dele_6c4f2c_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='activation_otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
